DROP TABLE IF EXISTS spendings;
DROP TABLE IF EXISTS users;

CREATE TABLE spendings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    month VARCHAR(10),
    description VARCHAR,
    amount REAL,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);